AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: go and Selenium on AWS Lambda
Resources:
  GoSelenium:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://go-selenium-stack/2117603eae7d49d1a634668f0a0b1da2
      Handler: handler
      Runtime: go1.x
      Timeout: 10
      Tracing: Active
      Layers:
      - Ref: LambdaLayer
      Events:
        api:
          Type: Api
          Properties:
            Path: /sc
            Method: GET
  GoSeleniumLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${GoSelenium}
      RetentionInDays: 1
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
      - go1.x
      Content:
        S3Bucket: selenium-stack
        S3Key: layer.zip
      Description: layer
      LayerName: selenium
Outputs:
  GoSeleniumAPI:
    Description: go and Selenium on AWS Lambda
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
