AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: go and Selenium on AWS Lambda
Resources:
  # Lambda
  GoSelenium:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: artifact
      Handler: handler
      Runtime: go1.x
      Timeout: 10
      Tracing: Active
      # Layers:
      #   - !Ref LambdaLayer
      Events:
        api:
          Type: Api 
          Properties:
            Path: /sc
            Method: GET

  # Log Group
  GoSeleniumLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${GoSelenium}
      RetentionInDays: 1

  # LambdaLayer:
  #   Type: AWS::Lambda::LayerVersion
  #   Properties:
  #     CompatibleRuntimes: 
  #       - go1.x
  #     Content: 
  #       S3Bucket: selenium-stack
  #       S3Key: layer.zip
  #     # ContentUri: "./layer/zip/layer.zip"
  #     Description: layer
  #     LayerName: selenium

Outputs:
  GoSeleniumAPI:
    Description: "go and Selenium on AWS Lambda"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"